/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ArtifactDownloadInfo
 */

public class ArtifactDownloadInfo {
  @SerializedName("downloadTimestamp")
  private String downloadTimestamp = null;

  @SerializedName("path")
  private String path = null;

  public ArtifactDownloadInfo downloadTimestamp(String downloadTimestamp) {
    this.downloadTimestamp = downloadTimestamp;
    return this;
  }

   /**
   * Get downloadTimestamp
   * @return downloadTimestamp
  **/
  @ApiModelProperty(value = "")
  public String getDownloadTimestamp() {
    return downloadTimestamp;
  }

  public void setDownloadTimestamp(String downloadTimestamp) {
    this.downloadTimestamp = downloadTimestamp;
  }

  public ArtifactDownloadInfo path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactDownloadInfo artifactDownloadInfo = (ArtifactDownloadInfo) o;
    return Objects.equals(this.downloadTimestamp, artifactDownloadInfo.downloadTimestamp) &&
        Objects.equals(this.path, artifactDownloadInfo.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadTimestamp, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactDownloadInfo {\n");
    
    sb.append("    downloadTimestamp: ").append(toIndentedString(downloadTimestamp)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

