/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IssueUsage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a list of IssueUsage entities.
 */
@ApiModel(description = "Represents a list of IssueUsage entities.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-02-26T16:22:21.476Z")
public class IssuesUsages {
  @SerializedName("href")
  private String href = null;

  @SerializedName("issueUsage")
  private List<IssueUsage> issueUsage = null;

  @SerializedName("count")
  private Integer count = null;

  public IssuesUsages href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public IssuesUsages issueUsage(List<IssueUsage> issueUsage) {
    this.issueUsage = issueUsage;
    return this;
  }

  public IssuesUsages addIssueUsageItem(IssueUsage issueUsageItem) {
    if (this.issueUsage == null) {
      this.issueUsage = new ArrayList<IssueUsage>();
    }
    this.issueUsage.add(issueUsageItem);
    return this;
  }

   /**
   * Get issueUsage
   * @return issueUsage
  **/
  @ApiModelProperty(value = "")
  public List<IssueUsage> getIssueUsage() {
    return issueUsage;
  }

  public void setIssueUsage(List<IssueUsage> issueUsage) {
    this.issueUsage = issueUsage;
  }

  public IssuesUsages count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssuesUsages issuesUsages = (IssuesUsages) o;
    return Objects.equals(this.href, issuesUsages.href) &&
        Objects.equals(this.issueUsage, issuesUsages.issueUsage) &&
        Objects.equals(this.count, issuesUsages.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, issueUsage, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssuesUsages {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    issueUsage: ").append(toIndentedString(issueUsage)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

